#!/usr/bin/env bash
# installs nginx
apt-get update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/boldboxer permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restarting Nginx service
service nginx restart
